name: Cleanup Old Releases and Workflows

on:
  schedule:
    - cron: '0 4 * * 1'  # 每周一凌晨4点执行清理
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: 删除旧的workflow运行记录
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 30
        keep_minimum_runs: 5

    - name: 删除旧的Releases
      uses: dev-drprasad/delete-older-releases@v0.3.2
      with:
        keep_latest: 10
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}